### ISSUE TITLE
new feature (target)

### ISSUE THREAD

**Issue by diegodblr** [MatthewClarkMay/geoip-attack-map#13]
I created a new feature. I removed the first table, the one that shows the colors and the protocols, and added a new one in which the quantity and the target ip appear. Thus it is possible to know which network ips are more and / or less attacked.

**Comment by MatthewClarkMay** [comment]
This isn't so much an issue, as it is a milestone. Perhaps you can create a pull request, or open up a project within this repository so I can review the code? Or you can just share the code here by dragging/dropping files.

**Comment by diegodblr** [comment]
I do not know how to play git. Where do I copy and paste the code?

**Comment by dmadisetti** [comment]
Click fork, click into the respective files and click edit. Then provide a pull request

I would recommend learning git for github:

https://help.github.com/articles/fork-a-repo/
https://try.github.io/levels/1/challenges/1

**Comment by diegodblr** [comment]
I think I got it. Kk
