### ISSUE TITLE
raspberry pi

### ISSUE THREAD

**Issue by 007scorpio** [MatthewClarkMay/geoip-attack-map#18]
Please can this be done on a raspberry pi 3.... 
Thanks

**Comment by eddie4** [comment]
There is no reason why it shouldn't but it depends on what you use to generate input. I use it for a honeypot which is to heavy for a raspberry pi. But the map it's self should work fine.

**Comment by MatthewClarkMay** [comment]
eddie4 is correct. Closing issue.
