### ISSUE TITLE
mapbox API limit reaced

### ISSUE THREAD

**Issue by eddie4** [MatthewClarkMay/geoip-attack-map#19]
Hi,

It seems that you included your own apikey for mapbox. So it seems you have run out of api calls. I registered my own account on mapbox however my account doesn't have the map that is being used ("mmay601.p9if994e") Is there any way you can share it or explain how to create the map that is currently used? 

Thank you in advanced.

**Comment by hhhh578** [comment]
Hey,

Don't know if this is what you're asking, but you can use the mapbox.satellite for a similar effect, just change it to:

_**var map = L.mapbox.map("map", "mapbox.satellite", {**_

Hope this helps!

**Comment by eddie4** [comment]
Indeed that was the fix I was looking for, Thank you !!!!
