### ISSUE TITLE
WebSocket connection refused

### ISSUE THREAD

**Issue by Gloomywind** [MatthewClarkMay/geoip-attack-map#2]
WebSocket connection to 'ws://127.0.0.1:8888/websocket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
![image](https://cloud.githubusercontent.com/assets/11408498/20662938/93e56ade-b590-11e6-9751-ebed03080658.png)

**Comment by toontong** [comment]
![image](https://cloud.githubusercontent.com/assets/416141/20701359/7e13bdba-b64d-11e6-9c3f-3d022610f2ea.png)

400 bad request on new WebSocket(ws://xxx)
