### ISSUE TITLE
Unable to parse logs from /var/log/syslog correctly

### ISSUE THREAD

**Issue by Xqution** [MatthewClarkMay/geoip-attack-map#21]
Hello, i just recently set up my geoip-attack-map, everything works fine when am using dummy traffic, i have a SIEM that has been configured to send logs to the Attackmap server but whenever i run Dataserver.py it shows NOT A VALID LOG. Is there a solution for this??

**Comment by mexbo** [comment]
I think you're not configured well.

**Comment by Jghost13** [comment]
Were you ever able to solve this issue?
