### ISSUE TITLE
为什么我的不能显示地图

### ISSUE THREAD

**Issue by mexbo** [MatthewClarkMay/geoip-attack-map#23]
Why can't my map be displayed? 
Everything else is right that the map is black.
@MatthewClarkMay

**Comment by amassi-network** [comment]
Hi
May be you have to create an account on mapbox and get a key to change in geoip-attack-map/AttackMapServer/static/map.js ? 

L.mapbox.accessToken = "pk.eyJ1IjoibW1heTYwMSIsImEiOiJjaWgyYWU3NWQweWx2d3ltMDl4eGk5eWY1In0.9YoOkALPP7zaoim34ZITxw";

**Comment by mexbo** [comment]
[img](https://github.com/mexbo/img-folder/blob/master/Attack%20Map.png)
This is the original map. I didn't make any changes.
But after I changed the key, it couldn't show the black map.
Why？

**Comment by mexbo** [comment]
OK,Thanks @amassi-network ,I solved the problem.

**Comment by mexbo** [comment]
Finally, I changed to the latest secret key, and the map was displayed.
