### ISSUE TITLE
mapbox background map is not being displayed

### ISSUE THREAD

**Issue by ToxicRoot** [MatthewClarkMay/geoip-attack-map#4]
All data is processed normally, but the mapbox background map is not rendered to web page as shown on the screen in attach. I've tried to generate a new access token - that did solve the 401 error code issue, but now I get the 404 when JS is trying to access the mapbox url. 
![img2](https://cloud.githubusercontent.com/assets/1440107/22505487/d0e973b0-e88c-11e6-89b4-b4ded42f95ee.PNG)
![img1](https://cloud.githubusercontent.com/assets/1440107/22505486/d0e9213a-e88c-11e6-95f9-36cd440f0e8c.PNG)

**Comment by MatthewClarkMay** [comment]
As of January 31, Mapbox Editor has been taken offline, so I need to migrate the project to Mapbox Studio. I am busy with work right now, but I will resolve the issue this weekend.

**Comment by ToxicRoot** [comment]
Yes, this crossed my mind :) good luck with the new API! Thx for the effort!

**Comment by amassi-network** [comment]
I add  <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.32.1/mapbox-gl.js'></script>
I replace  <script src='https://api.mapbox.com/mapbox.js/v2.3.0/mapbox.js'></script> by 
	<script src='https://api.mapbox.com/mapbox.js/v3.0.1/mapbox.js'></script>
I add  in  but not sure it s necessary
	<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.32.1/mapbox-gl.css' rel='stylesheet' />
and just change it var map = L.mapbox.map('map', 'mapbox.streets', {
                    center: [lat, long], // lat, long
                    zoom: 2
                    });
very simple but it s break my head 5 days

**Comment by ToxicRoot** [comment]
mapbox.streets to mapbox.dark ... to save the original 'dark' theme :) and you need your own API token, but that's not a problem

**Comment by MatthewClarkMay** [comment]
I had to select a MapBox plan before it would work again. Should be good now!
