### ISSUE TITLE
how can I make a same map just use my own token

### ISSUE THREAD

**Issue by zaxfenfeiyu** [MatthewClarkMay/geoip-attack-map#5]
I build the map in my server some days. 
But yesterday,I find the token have some problems.
It seems the token is out of time.
How can I use Mapbox and get a map same as yours with my own token.
Thanks!

**Comment by amassi-network** [comment]
reponse is here i think https://github.com/MatthewClarkMay/geoip-attack-map/issues/4

**Comment by ToxicRoot** [comment]
you need to adapt with your data this portion of code in AttackMapServer/index.html:

// link map
            L.mapbox.accessToken = "pk.eyJ1IjoibW1heTYwMSIsImEiOiJjaWgyYWU3NWQweWx2d3ltMDl4eGk5eWY1In0.9YoOkALPP7zaoim34ZITxw";
            var map = L.mapbox.map("map", "mmay601.p9if994e", {
                center: [0, 0], // lat, long
                zoom: 2
            });

**Comment by diegodblr** [comment]
Here I use 3 options: mapbox.satellite, mapbox.streets or mapbox.dark.

var map = L.mapbox.map("map", "mapbox.satellite", {

**Comment by zaxfenfeiyu** [comment]
Thank you!
